services:
  nginx:
    image: nginx:alpine
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./html:/usr/share/nginx/html:ro
    restart: unless-stopped
  caddy:
    image: caddy:alpine
    ports:
      - '8081:80'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./html:/usr/share/nginx/html/data:ro
      - ./dist:/usr/share/nginx/html/_template:ro
    restart: unless-stopped
