name: Pages
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose up -d
      - run: dd if=/dev/random of=./html/file1 bs=1M count=5
      - run: dd if=/dev/random of=./html/file2 bs=1M count=3
      - run: dd if=/dev/random of=./html/file3 bs=1M count=1
      - run: mkdir -p html/screenshots && cp promote/*.png ./html/screenshots
      - run: wget --mirror -p http://localhost:8081 -P ./example
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'example'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
