name: Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: corepack yarn install
      - run: corepack yarn vite build --base /_listingway
      - run: mv dist listingway
      - uses: actions/upload-artifact@v4
        with:
          name: listingway
          path: listingway
      - run: mkdir release && tar -czf ./release/listingway.tar.gz listingway
        if: ${{ contains(github.ref, 'refs/tags') }}
      - uses: elgohr/Github-Release-Action@v5
        if: ${{ contains(github.ref, 'refs/tags') }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.ref_name }}
          workdir: release
