name: Release
on:
  push:
    branches:
      - master
    tags:
      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: corepack yarn install
      - run: corepack yarn vite build --base /_listingway
      - run: mv dist listingway
      - uses: actions/upload-artifact@v4
        with:
          name: listingway
          path: listingway
